#!/bin/sh

# exit script if there is an error
set -e

echo "ENVIRONMENT: $RAILS_ENV"

# create or migrate existing database
bin/rails db:prepare

# remove pid file from previous session
rm -f "$APP_PATH"/tmp/pids/server.pid

exec "${@}"
